name: API Tests

on: [push]

jobs:
  test:
    runs-on:ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Java 17 einrichten
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: REST Assured Tests mit Maven ausführen
        run: mvn test